[package]
name = "chomp"
version = "0.1.0"
edition = "2021"
authors = ["Adam Hiatt"]
description = "A game where you get to eat chocolate with an AI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prompted = "0.2.7"
